### ISSUE TITLE
SSH Public Key Not working

### ISSUE THREAD

**Issue by kennetham** [sedouard/rails-restaurant#1]
Hi, I have `ssh-keygen -t rsa -b 2048 -C "user@domain.cloudapp.net"` and have copied the `id_rsa.pub` to Dokku.

However when I tried to deploy as mentioned `git remote add dokku dokku@domain.cloudapp.net.com:your_app_name`, it requested for a password and I couldn't deploy my app.

Please advise.

**Comment by sedouard** [comment]
you'll need to enter the same password when you push. You [can generate a password-less key](http://hortonworks.com/kb/generating-ssh-keys-for-passwordless-login/) which you wouldn't have to enter a password. This is simply the same thing as setting up an ssh key.

Feel free to close this out if that fixes your issue.

**Comment by kennetham** [comment]
@sedouard Thanks the issue had be resolved. However, a quick question to deploying dokku on azure, to setup the DNS with cloudapp.net, is it possible? If I were to use a custom domain, I would have to CNAME to point to cloudapp.net server am I right?

**Comment by sedouard** [comment]
You cannot use the .cloudapp.net domain because you don't own it. You must
use a domain name that you own. Grab one from name cheap or something.

**Comment by kennetham** [comment]
Got it!

**Comment by sedouard** [comment]
:+1:
