### ISSUE TITLE
Call out that this guide promotes dokku-alt

### ISSUE THREAD

**Issue by josegonzalez** [sedouard/rails-restaurant#3]
dokku-alt and dokku are completely separate projects, and at this point, both their internal code and the interfaces they provide have deviated significantly. 

If you can make it clear that the guide _doesn't_ use dokku, that would be ideal, as it reflects poorly on the dokku project.

Thanks in advance!

**Comment by sedouard** [comment]
Thanks for pointing that out @josegonzalez! I wrote this a while back when I was just learning about dokku. I think I'll just update the guide to use vanilla dokku with the postgres plugin. It'll be a bit simpler now that we have template-able deployment model.

**Comment by josegonzalez** [comment]
:+1: thanks!

**Comment by sedouard** [comment]
closed via https://github.com/sedouard/dokku-azure/pull/4. @josegonzalez reopen if you think there's something I missed.
